graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: false
    exception-handlers-enabled: true
  tools:
    schema-location-pattern: "**/*.graphqls"
    introspection-enabled: true


altair:
  enabled: true
  mapping: /altair
  endpoint.graphql: /graphql
  pageTitle: Altair
  props.resources.variables: graphqls/altair/variables.graphql