graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: false
    exception-handlers-enabled: true
  tools:
    schema-location-pattern: "**/*.graphqls"
    introspection-enabled: true

